---
# @see https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference
version: 2
updates:

  # Docker
  - package-ecosystem: "docker"
    directories:
      - "/python/fast-api-simple/{{cookiecutter.project_slug}}/"
      - "/python/simple/{{cookiecutter.project_slug}}/"
    schedule:
      interval: "weekly"
    assignees:
      - "bgaillard"

  # Poetry
  - package-ecosystem: "pip"
    directories:
      - "/python/fast-api-simple/{{cookiecutter.project_slug}}/"
      - "/python/simple/{{cookiecutter.project_slug}}/"
    groups:
      # Security updates
      development-security-updates:
        applies-to: "security-updates"
        dependency-type: development
      production-security-updates:
        applies-to: "security-updates"
        dependency-type: production
      # Version updates
      development-version-updates:
        applies-to: "version-updates"
        dependency-type: development
      production-version-updates:
        applies-to: "version-updates"
        dependency-type: production
    schedule:
      interval: "weekly"
    assignees:
      - "bgaillard"

  # UV
  - package-ecosystem: "uv"
    directories:
      - "/python/fast-api-simple/{{cookiecutter.project_slug}}/"
      - "/python/simple/{{cookiecutter.project_slug}}/"
    groups:
      # Security updates
      development-security-updates:
        applies-to: "security-updates"
        dependency-type: development
      production-security-updates:
        applies-to: "security-updates"
        dependency-type: production
      # Version updates
      development-version-updates:
        applies-to: "version-updates"
        dependency-type: development
      production-version-updates:
        applies-to: "version-updates"
        dependency-type: production
    schedule:
      interval: "weekly"
    assignees:
      - "bgaillard"
