# https://docs.astral.sh/uv/guides/integration/docker/#non-editable-installs

ARG PYTHON_VERSION=3.13

ARG USER=app
ARG GROUP=app


FROM python:${PYTHON_VERSION}-slim AS base

ARG GROUP
ARG GROUP_ID

ARG USER
ARG USER_ID

    # Enable bytecode compilation
ENV UV_COMPILE_BYTECODE=1 \
    # Copy from the cache instead of linking since it's a mounted volume
    UV_LINK_MODE=copy

# Setup a non-root user
#
# @see https://vsupalov.com/docker-shared-permissions/
RUN groupadd --system --gid $GROUP_ID $GROUP \
 && useradd --system --gid $GROUP_ID --uid $USER_ID --create-home $USER

# Change the working directory to the `app` directory
WORKDIR /app

RUN chown $USER:$GROUP /app


########################################################################################################################
# DEV
########################################################################################################################
FROM base AS dev

ARG USER

COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

RUN apt-get update \
    && apt-get install --no-install-recommends -y \
        # deps for pyright
        libatomic1

USER $USER

# Install dependencies
RUN --mount=type=cache,target=/root/.cache/uv \
    --mount=type=bind,source=uv.lock,target=uv.lock \
    --mount=type=bind,source=pyproject.toml,target=pyproject.toml \
    uv sync --locked --no-install-project --no-editable --group lint && \
    # Execute Pyright a first time to force install in Docker layer
    uvx pyright --version && \
    # Execute Ruff a first time to force install in Docker layer
    uvx ruff --version

# Copy the project into the intermediate image
ADD . /app

# Sync the project
RUN --mount=type=cache,target=/root/.cache/uv \
    uv sync --locked

# Configure correct rights
USER root
RUN chown -R $USER:$GROUP /app

# Place executables in the environment at the front of the path
ENV PATH="/app/.venv/bin:$PATH"

# Reset the entrypoint, don't invoke `uv`
ENTRYPOINT []

# Use the non-root user to run our application
USER $USER

CMD ["python", "-m", "app.main"]



########################################################################################################################
# PROD
########################################################################################################################

# The 'builder-prod' stage is used to create an optimized virtual environment for production use.
# We need a dedicated stage because we do not want 'uv' and 'uvx' to be included in the final image.
FROM base AS builder-prod
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

# Sync the project
RUN --mount=type=cache,target=/root/.cache/uv \
    --mount=type=bind,source=uv.lock,target=uv.lock \
    --mount=type=bind,source=pyproject.toml,target=pyproject.toml \
    uv sync --frozen --no-editable --no-dev --no-group lint


FROM base as prod

ARG GROUP
ARG USER

COPY --chown=$USER:$GROUP --from=builder-prod /app/.venv /app/.venv

# Copy the project into the intermediate image
ADD . /app

# Configure correct rights
RUN chown -R $USER:$GROUP /app

# Place executables in the environment at the front of the path
ENV PATH="/app/.venv/bin:$PATH"

# Reset the entrypoint, don't invoke `uv`
ENTRYPOINT []

# Use the non-root user to run our application
USER $USER

CMD ["python", "-m", "app.main"]
