SHELL := bash

APP := app

COLOR_BLUE := \e[34m
COLOR_NC := \e[0m
COLOR_YELLOW := \e[33m

DOCKERFILE ?= Dockerfile

# Why Podman over Docker?
#  - Deamonless
#  - Rootless
#  - Better security
#  - Allow to use the '--userns=keep-id' option which is great to mount volumes with the same user id as the host.
#
# @see https://github.com/mamba-org/micromamba-docker/issues/407#issuecomment-2088523507
PODMAN ?= podman

# Name of the OCI image to build
CONTAINER_IMAGE ?= bgaillard/$(APP)

UV ?= uv
UVX ?= uvx

# @see https://stackoverflow.com/questions/2214575/passing-arguments-to-make-run/14061796#14061796
ifneq ($(filter $(firstword $(MAKECMDGOALS)),add add-dev add-lint remove),)
  RUN_ARGS := $(wordlist 2,$(words $(MAKECMDGOALS)),$(MAKECMDGOALS))
  $(eval $(RUN_ARGS):;@:)
endif


.PHONY: add add-dev add-lint clear build build-docker lock-upgrade remove sync venv
## == Building ==
clear: clean  ## Alias for 'make clean'
clean:  ## Clean local build and temporary files
	find . -type f -name '*.py[co]' -delete -o -type d -name __pycache__ -delete
	rm -Rf .cache
	rm -Rf .coverage
	rm -Rf .pytest_cache
	rm -Rf .ruff_cache
	rm -Rf .venv
	rm -Rf htmlcov
	rm -Rf junit

build: ## Build the source distribution (i.e. sdist) and binary distribution (i.e. wheel)
	@ $(UV) build

build-docker: ## Build the production Docker image
	@ $(PODMAN) build -f $(DOCKERFILE) --pull --tag $(CONTAINER_IMAGE):prod .

add: ## Add a dependency
	@ $(UV) add $(RUN_ARGS)

add-dev: ## Add a dependency to the 'dev' group
	@ $(UV) add --dev $(RUN_ARGS)

add-lint: ## Add a development to the 'lint' group
	@ $(UV) add --group lint $(RUN_ARGS)

lock-upgrade: ## Update the dependencies in the 'uv.lock' file
	@ $(UV) lock --upgrade

remove: ## Remove a dependency
	@ $(UV) remove $(RUN_ARGS)

sync: ## Update the project's environment using the 'uv.lock' file
	@ $(UV) sync

venv: ## Create a virtual environment using the 'uv.lock' file
	@ $(UV) venv

##
## == Running ==
.PHONY: run run-dev
run: build-docker
run: ## Run the application using the production Docker image
	@ $(PODMAN) run --rm $(CONTAINER_IMAGE):prod

run-dev: build-dev
run-dev: ## Run the application using the development Docker image
	@ $(PODMAN) run \
		--rm \
		--volume $(PWD):/app \
		--workdir /app \
		$(CONTAINER_IMAGE):dev


##
## == Linting ==
.PHONY: lint lint-pyright lint-ruff lint-fix lint-fix-ruff
format: ## Alias for 'make lint-fix-ruff'
	@ $(UV) format --preview-features format

format-check: ## Alias for 'make lint-ruff'
	@ $(UV) format --check --preview-features format

lint: ## Lint with pyright and ruff
lint: lint-pyright lint-ruff

lint-pyright:  ## Lint with pyright
	@ echo -e "\n$(COLOR_YELLOW)lint$(COLOR_NC) - $(COLOR_BLUE)pyright$(COLOR_NC)"
	@ $(UVX) pyright ./app

lint-ruff:  ## Lint with ruff
	@ echo -e "\n$(COLOR_YELLOW)lint$(COLOR_NC) - $(COLOR_BLUE)ruff check$(COLOR_NC)"
	@ $(UVX) ruff check ./$(APP)

lint-fix:  ## Fix linting issues with ruff
lint-fix: lint-fix-ruff

lint-fix-ruff:  ## Fix linting issues with ruff
	@ echo -e "\n$(COLOR_YELLOW)lint-fix$(COLOR_NC) - $(COLOR_BLUE)ruff$(COLOR_NC)"
	@ $(UVX) ruff format ./$(APP)


##
## == Testing ==
.PHONY: test test-cov
test:  ## Run tests
ifdef K
	@ DOTENV=.env.test $(UV) run pytest -k "${K}"
else
	@ DOTENV=.env.test $(UV) run pytest --doctest-modules --junitxml=junit/test-results.xml $(APP)
endif

test-cov:  ## Run tests with coverage report
	DOTENV=.env.test $(UV) run pytest --cov=. --cov-report=html $(APP)
	@ echo "Coverage report has been written to htmlcov"
	@ xdg-open "file://$(abspath htmlcov)/index.html"

#
# File based recipes (advanced usage)
#

.DEFAULT_GOAL := help
help: Makefile
	@grep -E '(^[a-zA-Z_-]+:.*?##.*$$)|(^##)' $(MAKEFILE_LIST) | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[32m%-30s\033[0m %s\n", $$1, $$2}' | sed -e 's/\[32m## /[33m/'
