SHELL := bash

APP := app

COLOR_BLUE := \e[34m
COLOR_NC := \e[0m
COLOR_YELLOW := \e[33m

# Why Podman over Docker?
#  - Deamonless
#  - Rootless
#  - Better security
#  - Allow to use the '--userns=keep-id' option which is great to mount volumes with the same user id as the host.
#
# @see https://github.com/mamba-org/micromamba-docker/issues/407#issuecomment-2088523507
PODMAN ?= podman

# Name of the OCI image to build
CONTAINER_IMAGE ?= bgaillard/$(APP)

POETRY ?= poetry

# @see https://stackoverflow.com/questions/2214575/passing-arguments-to-make-run/14061796#14061796
ifneq ($(filter $(firstword $(MAKECMDGOALS)),poetry-add-group-dev poetry-add-group-main poetry-add-group-test),)
  RUN_ARGS := $(wordlist 2,$(words $(MAKECMDGOALS)),$(MAKECMDGOALS))
  $(eval $(RUN_ARGS):;@:)
endif


## == Building ==
.PHONY: clear builder-base build build-dev poetry-add-group-dev poetry-add-group-main poetry-add-group-test poetry-check poetry-update
clear:  ## Clear local build and temporary files
clean:
	find . -type f -name '*.py[co]' -delete -o -type d -name __pycache__ -delete
	rm -Rf .cache
	rm -Rf .pytest_cache
	rm -Rf .ruff_cache
	rm -Rf .venv
	rm -Rf htmlcov
	rm -Rf .coverage

build-docker: ## Build the production Docker image
	@ $(PODMAN) build --file $(DOCKERFILE) --target prod --pull --tag $(CONTAINER_IMAGE):prod .

add: ## Add a package to the 'main' group in the 'pyproject.toml' file and update the 'poetry.lock' file.
	@ $(POETRY) add --group main $(RUN_ARGS)

add-dev: ## Add a package to the 'dev' group in the 'pyproject.toml' file and update the 'poetry.lock' file.
	@ $(POETRY) add --group dev $(RUN_ARGS)

add-lint: ## Add a package to the 'test' group in the 'pyproject.toml' file and update the 'poetry.lock' file.
	@ $(POETRY) add --group lint $(RUN_ARGS)

check: ## Validates the content of the 'pyproject.toml' file and its consistency with the 'poetry.lock' file.
	@ $(POETRY) check

update: ## Create or update the 'poetry.lock' file (i.e. update Poetry dependencies)
	@ $(POETRY) update


##
## == Running ==
.PHONY: run run-dev
run: build
run: ## Run the application using the production Docker image
	@ $(PODMAN) run --rm $(CONTAINER_IMAGE):prod

run-dev: build-dev
run-dev: ## Run the application using the development Docker image
	@ $(PODMAN) run \
		--rm \
		--volume $(PWD):/app \
		--workdir /app \
		$(CONTAINER_IMAGE):dev


##
## == Linting ==
.PHONY: lint lint-pyright lint-ruff lint-fix lint-fix-ruff
lint: ## Lint with pyright and ruff
lint: lint-pyright lint-ruff

lint-pyright:  ## Lint with pyright
	@ echo -e "\n$(COLOR_YELLOW)lint$(COLOR_NC) - $(COLOR_BLUE)pyright$(COLOR_NC)"
	@ $(POETRY) run pyright ./app

lint-ruff:  ## Lint with ruff 
	@ echo -e "\n$(COLOR_YELLOW)lint$(COLOR_NC) - $(COLOR_BLUE)ruff check$(COLOR_NC)"
	@ $(POETRY) run ruff check ./$(APP)

lint-fix:  ## Fix linting issues with ruff
lint-fix: lint-fix-ruff

lint-fix-ruff:  ## Fix linting issues with ruff
	@ echo -e "\n$(COLOR_YELLOW)lint-fix$(COLOR_NC) - $(COLOR_BLUE)ruff$(COLOR_NC)"
	@ $(POETRY) run ruff format ./$(APP)


##
## == Testing ==
.PHONY: test test-cov
test:  ## Run tests
ifdef K
	@ DOTENV=.env.test $(POETRY) run pytest -k "${K}"
else
	@ DOTENV=.env.test $(POETRY) run pytest $(APP)
endif

test-cov:  ## Run tests with coverage report
	DOTENV=.env.test $(POETRY) run pytest --cov=. --cov-report=html $(APP)
	@ echo "Coverage report has been written to htmlcov"
	@ xdg-open "file://$(abspath htmlcov)/index.html"

#
# File based recipes (advanced usage)
#

.DEFAULT_GOAL := help
help: Makefile
	@grep -E '(^[a-zA-Z_-]+:.*?##.*$$)|(^##)' $(MAKEFILE_LIST) | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[32m%-30s\033[0m %s\n", $$1, $$2}' | sed -e 's/\[32m## /[33m/'
