ARG PYTHON_VERSION=3.14

########################################################################################################################
# BASE
########################################################################################################################
FROM python:${PYTHON_VERSION}-slim as base

# Setup a non-root user
RUN groupadd --system --gid 1000 app \
 && useradd --system --gid 1000 --uid 1000 app

# Python
ENV PYTHONUNBUFFERED=1 \
    # prevents python creating .pyc files
    PYTHONDONTWRITEBYTECODE=1 \
    VIRTUAL_ENV=/app/.venv \
    PATH="/app/.venv/bin:$PATH"

# Install the project into `/app`
WORKDIR /app


########################################################################################################################
# BUILDER
########################################################################################################################
FROM base as builder

ENV POETRY_CACHE_DIR=/tmp/poetry_cache \
    POETRY_VIRTUALENVS_CREATE=true \
    POETRY_VIRTUALENVS_IN_PROJECT=true \
    POETRY_NO_INTERACTION=1

RUN apt-get update && \
  apt-get install --no-install-recommends -y \
    # deps for installing poetry
    curl \
    # deps for building python deps
    build-essential && \
  curl -sSL https://install.python-poetry.org | python

COPY pyproject.toml poetry.lock /app/

RUN --mount=type=cache,target=$POETRY_CACHE_DIR \
  touch README.md && \
  export PATH="/root/.local/bin:$PATH" && \
  poetry install --compile --no-root --no-interaction --without=dev --without=lint && \
  rm README.md


FROM base as prod
COPY --chown=app:app --from=builder ${VIRTUAL_ENV} ${VIRTUAL_ENV}

USER $USER

COPY . /app

RUN chown -R app:app /app

CMD ["uvicorn", "--host", "0.0.0.0", "--port", "8000", "app.main:app"]
