---
name: python-fast-api-simple
on:
  push:
    paths:
      - 'python/fast-api-simple/**'
  pull_request:
    paths:
      - 'python/fast-api-simple/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository 
        uses: actions/checkout@v5
      # @see https://github.com/actions/setup-python/issues/967#issuecomment-2430610509
      - name: Set up Python 3.14
        uses: actions/setup-python@v6
        id: python
        with:
          python-version: 3.14
      - name: Install dependencies
        run: |
          pipx install cookiecutter
          pip install -U pytest
          pip install -U cookiecutter
        env:
          PIPX_DEFAULT_PYTHON: ${{ steps.python.outputs.python-path }}
      - name: Run tests
        run: |
          cd python/fast-api-simple
          make test
      - name: Upload pytest test results
        uses: actions/upload-artifact@v4
        with:
          name: pytest-results-python-fast-api-simple
          path: python/fast-api-simple/junit/test-results.xml
        # Use always() to always run this step to publish test results when there are test failures
        if: ${{ always() }}
